# executed before each script
- type: 'vars'
  vars:
    PersonAccount: contact:class:PersonAccount
    Person: contact:class:Person
    Employee: contact:mixin:Employee
    Configuration: core:class:PluginConfiguration
    Project: tracker:class:Project
    Issue: tracker:class:Issue
    Attachment: attachment:class:Attachment
    Teamspace: document:class:Teamspace
    Document: document:class:Document
    DefaultProject: tracker:project:DefaultProject
- type: 'default'
  _class: 'Configuration'
  data:
    space: 'core:space:Model'
- type: 'default'
  _class: 'Issue'
  collabFields:
    - 'description'
  data:
    space: 'tracker:project:DefaultProject'
    assignee: '${userPerson}'
    status: 'tracker:status:Backlog'
    priority: 0
    component: null
    dueDate: null
    milestone: null
    estimation: 0
    remainingTime: 0
    reportedTime: 0
    reports: 0
    attachedTo: 'tracker:ids:NoParent'
    attachedToClass: 'tracker:class:Issue'
    collection: 'subIssues'
    kind: 'tracker:taskTypes:Issue'
    rank: '#nextRank'
    relations: []
    parents: []
    childInfo: []
- type: 'default'
  _class: 'Document'
  collabFields:
    - 'content'
- type: 'default'
  _class: 'Attachment'
  data: 
    attachedToClass: 'Issue'
    collection: 'attachments'
    space: 'tracker:project:DefaultProject'
    type: 'image/gif'
    lastModified: '#now'
- type: 'default'
  _class: 'document:class:Document'
  data:
    attachedTo: 'document:ids:NoParent'
    attachedToClass: 'document:class:Document'
    collection: 'children'
    version: 0
    snapshots: 0
    space: '${teamSpace}'
- type: 'create'
  _class: 'Person'
  resultVariable: userPerson
  data: 
    space: contact:space:Contacts
    name: 'John Doe'
    city: ''
    avatarType: 'color'
    avatarProps:
      color: '#f868bc'
- type: 'mixin'
  _class: 'Person'
  mixin: 'Employee'
  data: 
    space: contact:space:Contacts
    _id: ${userPerson}
    active: true
- type: 'create'
  _class: 'contact:class:PersonAccount'
  resultVariable: userAccount
  data:
    email: 'info@hardcoreeng.com'
    role: 'OWNER'
    space: 'core:space:Model'
    person: ${userPerson}